export const SITE_CONFIG = {
  name: 'PRATHAM TECHCARE PVT LTD',
  tagline: 'Enterprise IT Solutions',
  shortName: 'PTC',
  description:
    'Pratham Tech Care delivers enterprise-grade IT infrastructure, managed services, cybersecurity, and cloud solutions trusted by businesses across India.',
  url: 'https://prathamtechcare.com',
  email: 'info@prathamtechcare.in',
  phone: '+91 70218 71288',
  // phone2: '+91 98765 43211',
  address: {
    line1: 'Shop No-01, B Wing, Saidham Building, Saibaba Rd, Jawaharnagar, Khar East',
    line2: 'Mumbai, Maharashtra 400055',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pin: '400055',
  },
  social: {
    linkedin: 'https://linkedin.com/company/prathamtechcare',
    twitter: 'https://twitter.com/prathamtechcare',
    facebook: 'https://facebook.com/prathamtechcare',
    youtube: 'https://youtube.com/@prathamtechcare',
  },
  founded: '2010',
  employees: '10+',
  projects: '75+',
  clients: '25+',
  uptime: '99.9%',
};
